### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by lazywei** [tleyden/docker#1]
I got this message when trying to

```
$ sudo docker run -ti $DOCKER_NVIDIA_DEVICES tleyden5iwx/caffe-gpu /bin/bash
flag provided but not defined: --device /dev/nvidia0:/dev/nvidia0
```

Thanks.

**Comment by tleyden** [comment]
I'm pretty sure that means your docker version is too old -- which version are you running?

I think you want 1.3 or later

**Comment by lazywei** [comment]
After I upgrade to 1.4.x, this error message still shows. It turns out I need to specify the flag in plain text instead of environment variables... this works:

```
sudo docker run -ti --device /dev/nvidia0:/dev/nvidia0 tleyden5iwx/caffe-gpu /bin/bash
```
