### ISSUE TITLE
Add volume to the image

### ISSUE THREAD

**Issue by lazywei** [tleyden/docker#2]
Hi,

I think it's very useful to have an volume in the image so that I can mount them to my host computer. In this way, we can put all the training/testing data or even log into that volume (aka shared folder), and then we can access these files outside the docker image. Also, we don't need to commit the process into image everytime we finish the traning/testing.
How do you feel about this?
Thanks.

**Comment by tleyden** [comment]
You can use a volume, just pass the -v flag on the command line when running docker.
